import './globals.css'
import { ClusterProvider } from '@/components/cluster/cluster-data-access'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { UiLayout } from '@/components/ui/ui-layout'
import { ReactQueryProvider } from './react-query-provider'
import { connectDB } from '@/utils/mongDb'

export const metadata = {
    title: 'Sukura',
    description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
    { label: 'Account', path: '/account' },
    { label: 'Clusters', path: '/clusters' },
    { label: 'Sukura Program', path: '/sukura' },
    { label: 'Admin Dashboard', path: '/admin' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
    connectDB().catch((err) => console.log(err))
    return (
        <html lang="en">
            <body data-theme="retro">
                <ReactQueryProvider>
                    <ClusterProvider>
                        <SolanaProvider>
                            <UiLayout links={links}>{children}</UiLayout>
                        </SolanaProvider>
                    </ClusterProvider>
                </ReactQueryProvider>
            </body>
        </html>
    )
}
