import './globals.css'
import { ClusterProvider } from '@/components/cluster/cluster-data-access'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { UiLayout } from '@/components/ui/ui-layout'
import { ReactQueryProvider } from './react-query-provider'
import { BodyWrapper } from './body-wrapper'

export const metadata = {
    title: 'Sukura',
    description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
    { label: 'Account', path: '/account' },
    { label: 'Clusters', path: '/clusters' },
    { label: 'Sukura Program', path: '/sukura' },
    { label: 'Admin Dashboard', path: '/admin' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" data-theme="sukura">
            <BodyWrapper>
                <ReactQueryProvider>
                    <ClusterProvider>
                        <SolanaProvider>
                            <UiLayout links={links}>{children}</UiLayout>
                        </SolanaProvider>
                    </ClusterProvider>
                </ReactQueryProvider>
            </BodyWrapper>
        </html>
    )
}
