'use client'

import Link from 'next/link'
import Image from 'next/image'
import * as React from 'react'
import { ReactNode, Suspense, useEffect, useRef } from 'react'
import toast, { Toaster } from 'react-hot-toast'

import { ClusterUiSelect, ExplorerLink } from '../cluster/cluster-ui'
import { WalletButton } from '../solana/solana-provider'
import SukuraLogo from '../../../public/SukuraLogo.svg'
import ArrowUp from '../../../public/arrowup.svg'
import '../../app/wallet.css'
import { usePathname } from 'next/navigation'
import '../../app/wallet.css'

export function UiLayout({
    children,
    links,
}: {
    children: ReactNode
    links: { label: string; path: string }[]
}) {
    const pathname = usePathname()

    return (
        <div className="h-full flex flex-col">
            <div className="navbar space-y-2 md:space-y-0 sm:px-12 sm:py-12 px-3 py-3">
                <div className="flex-1">
                    <Link className="normal-case text-3xl flex items-center gap-4" href="/">
                        <Image src={SukuraLogo} alt="Sukura Logo" />
                        SUKURA
                    </Link>
                </div>
                {pathname !== '/' && (
                    <div className="flex-none space-x-2">
                        <WalletButton />
                        <ClusterUiSelect />
                    </div>
                )}
            </div>
            <div className="flex-grow mx-4 lg:mx-auto">
                <Suspense
                    fallback={
                        <div className="text-center flex items-center justify-center">
                            <Spinner text="Loading mixer" overlay={true} />
                        </div>
                    }
                >
                    {children}
                </Suspense>
                <Toaster position="bottom-right" />
            </div>
            {/* <footer className="footer footer-center p-4 bg-base-300 text-base-content">
                <aside>
                    <p>
                        Generated by{' '}
                        <a
                            className="link hover:text-white"
                            href="https://github.com/solana-developers/create-solana-dapp"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            create-solana-dapp
                        </a>
                    </p>
                </aside>
            </footer> */}
        </div>
    )
}

export function AppModal({
    children,
    title,
    hide,
    show,
    submit,
    submitDisabled,
    submitLabel,
}: {
    children: ReactNode
    title: string
    hide: () => void
    show: boolean
    submit?: () => void
    submitDisabled?: boolean
    submitLabel?: string
}) {
    const dialogRef = useRef<HTMLDialogElement | null>(null)

    useEffect(() => {
        if (!dialogRef.current) return
        if (show) {
            dialogRef.current.showModal()
        } else {
            dialogRef.current.close()
        }
    }, [show, dialogRef])

    return (
        <dialog className="modal" ref={dialogRef}>
            <div className="modal-box space-y-5">
                <h3 className="font-bold text-lg">{title}</h3>
                {children}
                <div className="modal-action">
                    <div className="join space-x-2">
                        {submit ? (
                            <button
                                className="btn btn-xs lg:btn-md btn-primary"
                                onClick={submit}
                                disabled={submitDisabled}
                            >
                                {submitLabel || 'Save'}
                            </button>
                        ) : null}
                        <button onClick={hide} className="btn">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </dialog>
    )
}

export function AppHero({
    children,
    title,
    subtitle,
}: {
    children?: ReactNode
    title: ReactNode
    subtitle: ReactNode
}) {
    return (
        <div className="hero py-[64px]">
            <div className="hero-content text-center">
                <div className="max-w-2xl">
                    {typeof title === 'string' ? (
                        <h1 className="text-5xl font-bold">{title}</h1>
                    ) : (
                        title
                    )}
                    {typeof subtitle === 'string' ? <p className="py-6">{subtitle}</p> : subtitle}
                    {children}
                </div>
            </div>
        </div>
    )
}

export function ellipsify(str = '', len = 4) {
    if (str.length > 30) {
        return str.substring(0, len) + '..' + str.substring(str.length - len, str.length)
    }
    return str
}

export function useTransactionToast() {
    return (signature: string) => {
        toast.success(
            <div className={'text-center'}>
                <div className="text-lg">Transaction sent</div>
                <ExplorerLink
                    path={`tx/${signature}`}
                    label={'View Transaction'}
                    className="btn btn-xs btn-primary"
                />
            </div>
        )
    }
}

export function Button({
    children,
    onClick,
    className,
    disabled,
}: {
    children: ReactNode
    onClick?: () => void
    className?: string
    disabled?: boolean
}) {
    return (
        <button
            className={`btn bg-gradient-primary text-white btn-gradient-secondary btn-shadow ${className}`}
            onClick={onClick}
            disabled={disabled}
        >
            {children}
        </button>
    )
}

export function RangeSelector({
    amountPerWithdrawal,
    handleAmountChange,
}: {
    amountPerWithdrawal: number
    handleAmountChange: (amountPerWithdrawal: number) => void
}) {
    const poolAmountList = [0.1, 1, 10, 100]

    const handleRangeSelector = (index: number) => {
        const rangeSelector = document.querySelector('.range-selector')
        const prevButtons = document.querySelectorAll('.range-selector button')

        if (rangeSelector) {
            rangeSelector.style.setProperty('--onpointrx', `${index * 33.33333333}%`)

            prevButtons.forEach((btn) => {
                btn.style.backgroundColor = '#FFFFFF'
            })

            for (let i = 0; i < index; i++) {
                prevButtons[i].style.backgroundColor = '#7AFB96'
            }
        }
    }

    return (
        <div className="w-full">
            <h1 className="text-xl mb-4">Amount to Deposit</h1>
            <div className="w-full rounded-full bg-base-200 p-4">
                <div className="range-selector flex justify-between h-[8px] w-full bg-[#272930] rounded-full">
                    {poolAmountList.map((amount: number, index: number) => (
                        <button
                            key={amount}
                            aria-label="Radio"
                            className={`cursor-pointer ${amountPerWithdrawal === amount ? 'range-btn-active' : ''}`}
                            onClick={() => {
                                handleAmountChange(amount)
                                handleRangeSelector(index)
                            }}
                            id={`amount-${amount}`}
                        ></button>
                    ))}
                </div>
            </div>
            <div className="w-full flex justify-between rounded-full">
                {poolAmountList.map((amount: number) => (
                    <label
                        key={amount}
                        htmlFor={`amount-${amount}`}
                        className="cursor-pointer flex flex-col items-center text-neutral text-xs mt-4"
                    >
                        {amount} SOL
                    </label>
                ))}
            </div>
        </div>
    )
}

export function Spinner({ text, overlay = false }: { text?: string; overlay?: boolean }) {
    const defaultColor = '#D9D9D9'
    const activeColor = '#2D2D2D'

    const [activeIndex, setActiveIndex] = React.useState(0)

    useEffect(() => {
        const interval = setInterval(() => {
            setActiveIndex((prev) => (prev + 1) % 8)
        }, 200)

        return () => clearInterval(interval)
    }, [])

    return (
        <div
            className={`flex flex-col items-center ${overlay && 'fixed top-0 left-0 w-screen h-screen flex flex-col items-center justify-center backdrop-blur-sm overflow-hidden'}`}
        >
            <svg
                className="w-12 h-12"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 48 48"
                fill="none"
            >
                {[
                    { x: 22, y: 0, rotate: 0 },
                    { x: 33.9, y: 16.9, rotate: -135 },
                    { x: 36, y: 26, rotate: -90 },
                    { x: 31.1, y: 33.9, rotate: -45 },
                    { x: 22, y: 36, rotate: 0 },
                    { x: 8.4, y: 42.3, rotate: -135 },
                    { x: 0, y: 26, rotate: -90 },
                    { x: 5.6, y: 8.4, rotate: -45 },
                ].map((rect, index) => (
                    <rect
                        key={index}
                        x={rect.x}
                        y={rect.y}
                        width="4"
                        height="12"
                        rx="2"
                        fill={index === activeIndex ? activeColor : defaultColor}
                        transform={`rotate(${rect.rotate} ${rect.x} ${rect.y})`}
                    />
                ))}
            </svg>
            <p className="text-xl mt-6">{text}</p>
        </div>
    )
}
