'use client'

import Link from 'next/link'
import Image from 'next/image'
import * as React from 'react'
import { ReactNode, Suspense, useEffect, useRef } from 'react'
import toast, { Toaster } from 'react-hot-toast'

import { ClusterUiSelect, ExplorerLink } from '../cluster/cluster-ui'
import { WalletButton } from '../solana/solana-provider'
import SukuraLogo from '../../../public/SukuraLogo.svg'
import Check from '../../../public/SealCheck.svg'
import Cancel from '../../../public/X-toast.svg'
import ErrorImg from '../../../public/Warning.svg'
import '../../app/wallet.css'
import { usePathname } from 'next/navigation'
import '../../app/wallet.css'
import { BN, ProgramAccount } from '@coral-xyz/anchor'
import { PublicKey } from '@solana/web3.js'
import { UseQueryResult } from '@tanstack/react-query'

export function UiLayout({
    children,
    links,
}: {
    children: ReactNode
    links: { label: string; path: string }[]
}) {
    const pathname = usePathname()

    return (
        <div className="h-full flex flex-col">
            <div className="navbar space-y-2 md:space-y-0 sm:px-12 sm:py-12 px-3 py-3">
                <div className="flex-1">
                    <Link className="normal-case text-3xl flex items-center gap-4" href="/">
                        <Image src={SukuraLogo} alt="Sukura Logo" />
                        SUKURA
                    </Link>
                </div>
                {pathname !== '/' && (
                    <div className="flex-none space-x-2">
                        <WalletButton />
                        <ClusterUiSelect />
                    </div>
                )}
            </div>
            <div className="flex-grow mx-4 lg:mx-auto">
                <Suspense
                    fallback={
                        <div className="text-center flex items-center justify-center">
                            <Spinner text="Loading mixer" overlay={true} />
                        </div>
                    }
                >
                    {children}
                </Suspense>
                <Toaster position="bottom-right" />
            </div>
            {/* <footer className="footer footer-center p-4 bg-base-300 text-base-content">
                <aside>
                    <p>
                        Generated by{' '}
                        <a
                            className="link hover:text-white"
                            href="https://github.com/solana-developers/create-solana-dapp"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            create-solana-dapp
                        </a>
                    </p>
                </aside>
            </footer> */}
        </div>
    )
}

export function AppModal({
    children,
    title,
    hide,
    show,
    submit,
    submitDisabled,
    submitLabel,
}: {
    children: ReactNode
    title: string
    hide: () => void
    show: boolean
    submit?: () => void
    submitDisabled?: boolean
    submitLabel?: string
}) {
    const dialogRef = useRef<HTMLDialogElement | null>(null)

    useEffect(() => {
        if (!dialogRef.current) return
        if (show) {
            dialogRef.current.showModal()
        } else {
            dialogRef.current.close()
        }
    }, [show, dialogRef])

    return (
        <dialog className="modal" ref={dialogRef}>
            <div className="modal-box space-y-5">
                <h3 className="font-bold text-lg">{title}</h3>
                {children}
                <div className="modal-action">
                    <div className="join space-x-2">
                        {submit ? (
                            <button
                                className="btn btn-xs lg:btn-md btn-primary"
                                onClick={submit}
                                disabled={submitDisabled}
                            >
                                {submitLabel || 'Save'}
                            </button>
                        ) : null}
                        <button onClick={hide} className="btn">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </dialog>
    )
}

export function AppHero({
    children,
    title,
    subtitle,
}: {
    children?: ReactNode
    title: ReactNode
    subtitle: ReactNode
}) {
    return (
        <div className="hero py-[64px]">
            <div className="hero-content text-center">
                <div className="max-w-2xl">
                    {typeof title === 'string' ? (
                        <h1 className="text-5xl font-bold">{title}</h1>
                    ) : (
                        title
                    )}
                    {typeof subtitle === 'string' ? <p className="py-6">{subtitle}</p> : subtitle}
                    {children}
                </div>
            </div>
        </div>
    )
}

export function ellipsify(str = '', len = 4) {
    if (str.length > 30) {
        return str.substring(0, len) + '..' + str.substring(str.length - len, str.length)
    }
    return str
}

export function formatError(err: any) {
    return err.message.replace(/Error:\s*/g, '')
}

export function parseSimulationError(logs: string[]) {
    let program = ''
    let instruction = ''
    let reason = ''
    let details = {}

    for (const log of logs) {
        if (log.includes('invoke')) {
            program = log.split(' ')[1] // Extract program ID
        }
        if (log.includes('Instruction:')) {
            instruction = log.split(': ')[1] // Extract instruction name
        }
        if (log.includes('Transfer: insufficient lamports')) {
            reason = 'Insufficient balance'
            const match = log.match(/(\d+), need (\d+)/)
            if (match) {
                details = {
                    attempted_transfer: `${parseInt(match[2]) / 1e9} SOL`,
                    available_balance: `${parseInt(match[1]) / 1e9} SOL`,
                }
            }
        }
    }

    return {
        error: 'Transaction simulation failed',
        failing_instruction: 2,
        program,
        instruction,
        reason,
        details,
        suggestions: [
            "Check the sender's balance before attempting the deposit.",
            'Reduce the deposit amount.',
            'Ensure the correct account is used for funding.',
        ],
    }
}

export function useTransactionToast() {
    return (signature: string) => {
        toast.custom(
            <div className="flex items-center w-[400px]  justify-between bg-[#232837] rounded-[16px] p-4 sm:w-[700px] flex-wrap">
                <div className="flex items-center gap-4">
                    <Image src={Check} alt="check" />
                    <span className="text-lg text-white">Transaction Successful</span>
                </div>
                <ExplorerLink
                    path={`tx/${signature}`}
                    label={'View Transaction'}
                    className="btn bg-[#4A5167] text-white self-center order-1 mt-6 basis-full sm:order-0 sm:mt-0"
                />
                <Image
                    className="cursor-pointer order-0 sm:order-1"
                    src={Cancel}
                    alt="cancel"
                    onClick={() => toast.remove()}
                />
            </div>
        )
    }
}

export function useErrorToast() {
    return (main: string, sub: string) => {
        toast.custom(
            <div className="flex items-center w-[500px] justify-between p-4 bg-[#232837] rounded-[16px] bg-gradient-error error-toast">
                <div className="flex items-center w-full h-full">
                    <div className="mr-8">
                        <Image src={ErrorImg} alt="error" />
                    </div>
                    <div className="flex flex-col">
                        <span className="text-lg text-white">{main}</span>
                        <span>{sub}</span>
                    </div>
                </div>
                <Image
                    className="cursor-pointer"
                    src={Cancel}
                    alt="cancel"
                    onClick={() => toast.remove()}
                />
            </div>
        )
    }
}

export function Button({
    children,
    onClick,
    className,
    disabled,
}: {
    children: ReactNode
    onClick?: () => void
    className?: string
    disabled?: boolean
}) {
    return (
        <button
            className={`btn bg-gradient-primary text-white btn-gradient-secondary btn-shadow ${className}`}
            onClick={onClick}
            disabled={disabled}
        >
            {children}
        </button>
    )
}

interface MerkleTree {
    levels: number
    filledSubtrees: number[][]
    roots: number[][]
    currentRootIndex: BN
    nextIndex: number
    zeros: number[][]
}

interface ProgramAccountData {
    merkleTree: MerkleTree
    merkleRoot: number[]
    commitments: number[][]
    nullifiersHashes: number[][]
    amountPerWithdrawal: BN
    nonce: number
    vault: PublicKey
}

type Accounts = UseQueryResult<ProgramAccount<ProgramAccountData>[], Error>

export function RangeSelector({
    amountPerWithdrawal,
    handleAccountChange,
    accounts,
}: {
    amountPerWithdrawal: number
    handleAccountChange: (account: PublicKey, amount: number) => void
    accounts: Accounts
}) {
    const handleRangeSelector = (index: number) => {
        const rangeSelector = document.querySelector('.range-selector')
        const prevButtons = document.querySelectorAll('.range-selector button')

        if (rangeSelector) {
            rangeSelector.style.setProperty('--onpointrx', `${index * 33.33333333}%`)

            prevButtons.forEach((btn) => {
                btn.style.backgroundColor = '#FFFFFF'
            })

            for (let i = 0; i < index; i++) {
                prevButtons[i].style.backgroundColor = '#7AFB96'
            }
        }
    }
    const poolAmountList = [0.1, 1, 10, 100]

    return (
        <div className="w-full">
            <h1 className="text-xl mb-4">Amount to Deposit</h1>
            <div className="w-full rounded-full bg-base-200 p-4">
                <div className="range-selector flex justify-between h-[8px] w-full bg-[#272930] rounded-full">
                    {accounts.data
                        ?.sort(
                            (a, b) =>
                                a.account.amountPerWithdrawal.toNumber() -
                                b.account.amountPerWithdrawal.toNumber()
                        )
                        .map((account, index) => (
                            <button
                                key={account.publicKey.toString()}
                                aria-label="Radio"
                                className={`cursor-pointer ${amountPerWithdrawal === account.account.amountPerWithdrawal.toNumber() ? 'range-btn-active' : ''}`}
                                onClick={() => {
                                    handleAccountChange(
                                        account.publicKey,
                                        account.account.amountPerWithdrawal.toNumber()
                                    )
                                    handleRangeSelector(index)
                                }}
                                id={`amount-${account.account.amountPerWithdrawal.toNumber()}`}
                            ></button>
                        ))}
                </div>
            </div>
            <div className="w-full flex justify-between rounded-full">
                {poolAmountList.map((amount: number) => (
                    <label
                        key={amount}
                        htmlFor={`amount-${amount}`}
                        className="cursor-pointer flex flex-col items-center text-neutral text-xs mt-4"
                    >
                        {amount} SOL
                    </label>
                ))}
            </div>
        </div>
    )
}

export function Spinner({ text, overlay = false }: { text?: string; overlay?: boolean }) {
    const defaultColor = '#D9D9D9'
    const activeColor = '#2D2D2D'

    const [activeIndex, setActiveIndex] = React.useState(0)

    useEffect(() => {
        const interval = setInterval(() => {
            setActiveIndex((prev) => (prev + 1) % 8)
        }, 200)

        return () => clearInterval(interval)
    }, [])

    return (
        <div
            className={`flex flex-col items-center z-50 ${overlay && 'fixed top-0 left-0 w-screen h-screen flex flex-col items-center justify-center backdrop-blur-[10px] overflow-hidden'}`}
        >
            <svg
                className="w-12 h-12"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 48 48"
                fill="none"
            >
                {[
                    { x: 22, y: 0, rotate: 0 },
                    { x: 33.9, y: 16.9, rotate: -135 },
                    { x: 36, y: 26, rotate: -90 },
                    { x: 31.1, y: 33.9, rotate: -45 },
                    { x: 22, y: 36, rotate: 0 },
                    { x: 8.4, y: 42.3, rotate: -135 },
                    { x: 0, y: 26, rotate: -90 },
                    { x: 5.6, y: 8.4, rotate: -45 },
                ].map((rect, index) => (
                    <rect
                        key={index}
                        x={rect.x}
                        y={rect.y}
                        width="4"
                        height="12"
                        rx="2"
                        fill={index === activeIndex ? activeColor : defaultColor}
                        transform={`rotate(${rect.rotate} ${rect.x} ${rect.y})`}
                    />
                ))}
            </svg>
            <p className="text-xl mt-6">{text}</p>
        </div>
    )
}
